AWSTemplateFormatVersion: '2010-09-09'
Description: "Automation Lab"

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: "Environment to deploy to"

  SecretName:
    Type: String
    Description: "Default secret name for iam user"
    Default: IAMUserTempPassword

Resources:
  TempUserPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName
      GenerateSecretString:
        SecretStringTemplate: '{"username": "tempuser"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: "!@#$%^&*()_+-=[]{}|;:,.<>?"

  S3UserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "AutomationLabUsers"
      Policies:
        - PolicyName: "ListALLBuckets"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              Sid: "ListAllBuckets"
              Effect: "Allow"
              Action:
                - "S3:ListAllMyBuckets"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/IAMUserChangePassword"

  EC2UserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "EC2Users"
      Policies:
        - PolicyName: "EC2FullAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              Sid: "ViewEC2"
              Effect: "Allow"
              Action:
                - "ec2:DescribeInstances"
                - "ec2:DescribeInstanceStatus"
                - "ec2:DescribeImages"
                - "ec2:DescribeKeyPairs"
                - "ec2:DescribeSecurityGroups"
                - "ec2:DescribeVpcs"
                - "ec2:DescribeSubnets"
                - "ec2:DescribeAvailabilityZones"
                - "ec2:DescribeInstanceTypes"
                - "ec2:RunInstances"
                - "ec2:CreateTags"
              Resource: "*"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/IAMUserChangePassword"

  EC2User2Boundary:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: "ec2-user2-boundary"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowEverythingExceptRunInstances"
            Effect: "Allow"
            NotAction: "ec2:RunInstances"
            Resource: "*"


  FirstEC2User:
    Type: AWS::IAM::User
    Properties:
      UserName: "ec2-user1"
      LoginProfile:
        Password: !Sub '{{resolve:secretsmanager:${TempUserPassword}:SecretString:password}}'
        PasswordResetRequired: true
      Groups:
        - !Ref EC2UserGroup

  SecondEC2User:
    Type: AWS::IAM::User
    Properties:
      UserName: "ec2-user2"
      PermissionsBoundary: !Ref EC2User2Boundary
      LoginProfile:
        Password: !Sub '{{resolve:secretsmanager:${TempUserPassword}:SecretString:password}}'
        PasswordResetRequired: true
      Groups:
        - !Ref EC2UserGroup
      Policies:
        - PolicyName: "DenyCreateInstance"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              Sid: "DenyCreateInstance"
              Effect: "Deny"
              Action: "ec2:RunInstances"
              Resource: "*"

  S3User:
    Type: AWS::IAM::User
    Properties:
      UserName: "s3-user"
      LoginProfile:
        Password: !Sub '{{resolve:secretsmanager:${TempUserPassword}:SecretString:password}}'
        PasswordResetRequired: true
      Groups:
        - !Ref S3UserGroup
